import{S as M,a as g,i as l}from"./assets/vendor-MjawMu3A.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const m=document.querySelector(".gallery");class B{constructor(e,a){this.buttonEl=e,this.hiddenClass=a}showLoadMoreButton(){this.buttonEl.classList.remove(this.hiddenClass)}hideLoadMoreButton(){this.buttonEl.classList.add(this.hiddenClass)}}class P{constructor(e,a){this.loader=e,this.hiddenClass=a}showLoader(){this.loader.classList.remove(this.hiddenClass)}hideLoader(){this.loader.classList.add(this.hiddenClass)}}let d=null;function E(){d?d.refresh():d=new M(".gallery a",{captions:!0,captionDelay:250})}function p(o){const e=o.map(({webformatURL:a,largeImageURL:i,tags:r,likes:s,views:u,comments:b,downloads:w})=>`<li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img 
              class="gallery-image" 
              src="${a}" 
              alt="${r}" 
            />
          </a>
          
          <ul class="image-description">
          <li class="image-description-item">Likes <span class="description-numbers">${s}</span></li>
          <li class="image-description-item">Views <span class="description-numbers">${u}</span></li>
          <li class="image-description-item">Comments <span class="description-numbers">${b}</span></li>
          <li class="image-description-item">Download <span class="description-numbers">${w}</span></li>
          </ul>
        </li>`).join("");m.insertAdjacentHTML("beforeend",e),queueMicrotask(E)}function q(){m.innerHTML="",d&&(d.destroy(),d=null)}const x="https://pixabay.com/api",S="52901164-552010a54c9c54893e8a3cd4c";g.defaults.baseURL=x;async function f({page:o=1,per_page:e=20,q:a=""}={}){try{return(await g.get("/",{params:{page:o,per_page:e,q:a,key:S,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const v=document.querySelector(".form");document.querySelector(".gallery");const R=document.querySelector(".loader"),y=document.querySelector('[data-action="load-more"]'),t={page:1,per_page:15,q:"",maxPage:0},n=new B(y,"is-hidden");n.hideLoadMoreButton();const c=new P(R,"is-hidden");c.hideLoader();function $(){const o=document.querySelector(".gallery-image");if(!o)return 0;const{height:e}=o.getBoundingClientRect();return e}async function L(o=2){await new Promise(a=>requestAnimationFrame(a));const e=$();e>0&&window.scrollBy({top:e*o,behavior:"smooth"})}v.addEventListener("submit",C);y.addEventListener("click",I);let h=!1;async function C(o){o.preventDefault(),q();const e=o.currentTarget;if(t.q=e.elements.search.value.trim(),t.page=1,t.maxPage=1,!t.q){l.error({title:"Error",message:"Write a request",position:"topRight"}),e.reset();return}h=!0,c.showLoader(),n.hideLoadMoreButton();try{const{hits:a,total:i}=await f(t);if(t.maxPage=Math.ceil(i/t.per_page),console.log(i),console.log(t.maxPage,"params.maxPage"),console.log(t.page,"params.page"),a.length===0){c.hideLoader(),n.hideLoadMoreButton(),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(a),await L(),c.hideLoader(),t.maxPage>1?n.showLoadMoreButton():(n.hideLoadMoreButton(),l.info({title:"End",message:"You have reached the end of the results.",position:"topRight"}))}catch(a){l.error({title:"Error",message:`There is a problem during query ${a}`,position:"topRight"})}finally{c.hideLoader(),e.reset(),h=!1}}async function I(){if(h)return;if(t.page=Number(t.page)||1,t.maxPage=Number(t.maxPage)||1,t.page>=t.maxPage){l.info({title:"End",message:"You have reached the end of the results.",position:"topRight"}),n.hideLoadMoreButton();return}const o=t.page+1;h=!0,c.showLoader(),n.hideLoadMoreButton();try{const{hits:e}=await f({...t,page:o});t.page=o,p(e),await L()}catch(e){l.error({title:"Error",message:`There is a problem during query ${e}`,position:"topRight"})}finally{c.hideLoader(),h=!1,t.page<t.maxPage?n.showLoadMoreButton():(n.hideLoadMoreButton(),l.info({title:"End",message:"You have reached the end of the results.",position:"topRight"}))}}
//# sourceMappingURL=index.js.map
