import{a as h,S as M,i as d}from"./assets/vendor-CcCOw5fX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const m=document.querySelector(".gallery-list");class w{constructor(t,o){this.buttonEl=t,this.hiddenClass=o}showLoadMoreButton(){this.buttonEl.classList.remove(this.hiddenClass)}hideLoadMoreButton(){this.buttonEl.classList.add(this.hiddenClass)}}class E{constructor(t,o){this.loader=t,this.hiddenClass=o}showLoader(){this.loader.classList.remove(this.hiddenClass)}hideLoader(){this.loader.classList.add(this.hiddenClass)}}function p(r){const t=r.map(({webformatURL:o,largeImageURL:i,tags:e,likes:s,views:c,comments:L,downloads:b})=>`<li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img 
              class="gallery-image" 
              src="${o}" 
              alt="${e}" 
            />
          </a>
          
          <ul class="image-description">
          <li class="image-description-item">Likes <span class="description-numbers">${s}</span></li>
          <li class="image-description-item">Views <span class="description-numbers">${c}</span></li>
          <li class="image-description-item">Comments <span class="description-numbers">${L}</span></li>
          <li class="image-description-item">Download <span class="description-numbers">${b}</span></li>
          </ul>
        </li>`).join("");m.insertAdjacentHTML("beforeend",t)}function q(){m.innerHTML=""}const B="https://pixabay.com/api",S="52901164-552010a54c9c54893e8a3cd4c";h.defaults.baseURL=B;function g({page:r=1,per_page:t=20,q:o=""}={}){return h.get("/",{params:{page:r,per_page:t,q:o,key:S,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:i})=>i)}const P=document.querySelector(".form");document.querySelector(".gallery-list");const v=document.querySelector(".loader"),u=document.querySelector('[data-action="load-more"]'),a={page:1,per_page:15,q:"",maxPage:0},n=new w(u,"is-hidden");n.hideLoadMoreButton();const l=new E(v,"is-hidden");l.hideLoader();let f=new M(".gallery-list a",{captions:!0,captionDelay:250});P.addEventListener("submit",x);async function x(r){r.preventDefault(),q();const t=r.currentTarget;if(a.q=t.elements.search.value.trim(),!a.q){d.error({title:"Error",message:"Write a request",position:"topRight"}),t.reset();return}l.showLoader(),n.hideLoadMoreButton();try{const{hits:o,total:i}=await g(a);a.maxPage=Math.ceil(i/a.per_page);const e=o;if(console.log("total",i),p(e),f.refresh(),e.length===0){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}a.maxPage>1?(n.showLoadMoreButton(),l.hideLoader(),u.addEventListener("click",y)):(n.hideLoadMoreButton(),l.hideLoader())}catch(o){d.error({title:"Error",message:`There is a problem during query ${o}`,position:"topRight"})}finally{t.reset()}}async function y(){a.page+=1,l.showLoader(),n.hideLoadMoreButton();try{const{hits:r}=await g(a);p(r),f.refresh(),console.log("params.page",a.page),console.log("params.maxPage",a.maxPage)}catch(r){d.error({title:"Error",message:`There is a problem during query ${r}`,position:"topRight"})}finally{a.page===a.maxPage?(n.hideLoadMoreButton,l.hideLoader(),u.removeEventListener("click",y)):(n.showLoadMoreButton(),l.hideLoader())}}
//# sourceMappingURL=index.js.map
