import{a as h,S as B,i as d}from"./assets/vendor-CcCOw5fX.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const m=document.querySelector(".gallery");class M{constructor(e,o){this.buttonEl=e,this.hiddenClass=o}showLoadMoreButton(){this.buttonEl.classList.remove(this.hiddenClass)}hideLoadMoreButton(){this.buttonEl.classList.add(this.hiddenClass)}}class q{constructor(e,o){this.loader=e,this.hiddenClass=o}showLoader(){this.loader.classList.remove(this.hiddenClass)}hideLoader(){this.loader.classList.add(this.hiddenClass)}}function g(r){const e=r.map(({webformatURL:o,largeImageURL:a,tags:t,likes:s,views:c,comments:w,downloads:b})=>`<li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img 
              class="gallery-image" 
              src="${o}" 
              alt="${t}" 
            />
          </a>
          
          <ul class="image-description">
          <li class="image-description-item">Likes <span class="description-numbers">${s}</span></li>
          <li class="image-description-item">Views <span class="description-numbers">${c}</span></li>
          <li class="image-description-item">Comments <span class="description-numbers">${w}</span></li>
          <li class="image-description-item">Download <span class="description-numbers">${b}</span></li>
          </ul>
        </li>`).join("");m.insertAdjacentHTML("beforeend",e)}function S(){m.innerHTML=""}const E="https://pixabay.com/api",v="52901164-552010a54c9c54893e8a3cd4c";h.defaults.baseURL=E;function p({page:r=1,per_page:e=20,q:o=""}={}){return h.get("/",{params:{page:r,per_page:e,q:o,key:v,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:a})=>a)}const P=document.querySelector(".form");document.querySelector(".gallery");const $=document.querySelector(".loader"),u=document.querySelector('[data-action="load-more"]'),i={page:1,per_page:15,q:"",maxPage:0},n=new M(u,"is-hidden");n.hideLoadMoreButton();const l=new q($,"is-hidden");l.hideLoader();let f=new B(".gallery a",{captions:!0,captionDelay:250});function C(){const r=document.querySelector(".gallery-image");if(!r)return 0;const{height:e}=r.getBoundingClientRect();return e}async function y(r=2){await new Promise(o=>requestAnimationFrame(o));const e=C();e>0&&window.scrollBy({top:e*r,behavior:"smooth"})}P.addEventListener("submit",x);u.addEventListener("click",L);async function x(r){r.preventDefault(),S();const e=r.currentTarget;if(i.q=e.elements.search.value.trim(),!i.q){d.error({title:"Error",message:"Write a request",position:"topRight"}),e.reset();return}l.showLoader(),n.hideLoadMoreButton();try{const{hits:o,total:a}=await p(i);i.maxPage=Math.ceil(a/i.per_page);const t=o;if(t.length===0){l.hideLoader(),n.hideLoadMoreButton(),d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t),f.refresh(),await y(),l.hideLoader(),i.maxPage>1?n.showLoadMoreButton():n.hideLoadMoreButton()}catch(o){d.error({title:"Error",message:`There is a problem during query ${o}`,position:"topRight"})}finally{e.reset()}}async function L(){i.page+=1,l.showLoader(),n.hideLoadMoreButton();try{const{hits:r}=await p(i);g(r),f.refresh(),await y()}catch(r){d.error({title:"Error",message:`There is a problem during query ${r}`,position:"topRight"})}finally{l.hideLoader(),i.page===i.maxPage?(n.hideLoadMoreButton(),u.removeEventListener("click",L)):n.showLoadMoreButton()}}
//# sourceMappingURL=index.js.map
